import numpy as np

import pormake


def test_node_bb_basic_properties(database):
    bb = database.get_bb("N10")
    assert isinstance(bb, pormake.BuildingBlock)
    assert bb.n_atoms == 12
    assert bb.n_connection_points == 3
    assert bb.is_node is True
    assert bb.is_edge is False


def test_edge_bb_is_edge(database):
    bb = database.get_bb("E41")
    assert bb.n_atoms == 8
    assert bb.n_connection_points == 2
    assert bb.is_edge is True
    assert bb.is_node is False


def test_connection_point_indices_match_count(database):
    bb = database.get_bb("N409")
    assert bb.n_connection_points == 4
    assert len(bb.connection_point_indices) == 4
    # connection_points are the positions at those indices
    assert bb.connection_points.shape == (4, 3)


def test_copy_is_independent(database):
    bb = database.get_bb("N10")
    clone = bb.copy()
    # Same data
    assert clone.n_atoms == bb.n_atoms
    assert clone.n_connection_points == bb.n_connection_points
    np.testing.assert_allclose(
        clone.atoms.get_positions(), bb.atoms.get_positions()
    )
    # Mutating the clone must not touch the original (deepcopy)
    clone.atoms.set_positions(clone.atoms.get_positions() + 1.0)
    assert not np.allclose(
        clone.atoms.get_positions(), bb.atoms.get_positions()
    )


def test_xyz_parser_reads_bond_block(tmp_path):
    xyz = tmp_path / "cn_with_bonds.xyz"
    xyz.write_text(
        "4\n"
        "   cn_with_bonds\n"
        "X    1.0 0.0 0.0\n"
        "X    -0.5 0.866 0.0\n"
        "X    -0.5 -0.866 0.0\n"
        "C    0.0 0.0 0.0\n"
        "   0    3 S\n"
        "   1    3 S\n"
        "   2    3 S\n"
    )
    bb = pormake.BuildingBlock(str(xyz))
    assert bb.name == "cn_with_bonds"
    assert bb.n_atoms == 4
    assert bb.n_connection_points == 3
    assert bb.is_node is True
    assert len(bb.bonds) == 3
    assert list(bb.bond_types) == ["S", "S", "S"]


def test_xyz_parser_auto_generates_bonds_when_absent(tmp_path):
    xyz = tmp_path / "cn_no_bonds.xyz"
    xyz.write_text(
        "4\n"
        "   cn_no_bonds\n"
        "X    1.0 0.0 0.0\n"
        "X    -0.5 0.866 0.0\n"
        "X    -0.5 -0.866 0.0\n"
        "C    0.0 0.0 0.0\n"
    )
    bb = pormake.BuildingBlock(str(xyz))
    assert bb.n_connection_points == 3
    # Bonds are auto-generated by distance threshold (3 X-C bonds)
    pairs = {tuple(sorted(pair)) for pair in np.array(bb.bonds).tolist()}
    assert pairs == {(0, 3), (1, 3), (2, 3)}
    assert list(bb.bond_types) == ["S", "S", "S"]
